export enum ETransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT = 'LOAN_REPAYMENT',
  INTEREST_CREDIT = 'INTEREST_CREDIT',
  FEE_CHARGE = 'FEE_CHARGE',
  LATE_FEE_CHARGE = 'LATE_FEE_CHARGE',
}
