#!/bin/bash
PROTO_DIR="assets/proto"
mkdir -p "$PROTO_DIR"
for file in $(find apps -name "*.proto"); do
  filename=$(basename "$file")
  echo "// This file is autogenerated by \`scripts/copy-protos.sh\`, do not edit it manually" > "$PROTO_DIR/$filename"
  cat "$file" >> "$PROTO_DIR/$filename"
  echo "✓ Copied: $filename"
done
