export enum ELoanStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DISBURSED = 'DISBURSED',
  ACTIVE = 'ACTIVE',
  FULLY_PAID = 'FULLY_PAID',
  DEFAULTED = 'DEFAULTED',
  REJECTED = 'REJECTED',
}
